## 환경셋팅

In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
cd /content/drive/MyDrive/Colab Notebooks/Github/where-is-my-home-ai

/content/drive/MyDrive/Colab Notebooks/Github/where-is-my-home-ai

In [3]:
import pandas as pd
import numpy as np

## 데이터 가져오기

In [4]:
for dirname, _, filenames in os.walk('data/'):
    for filename in filenames:
      print(os.path.join(dirname, filename))

data/data_set.csv
data/data_set_div_sigugun.csv

In [6]:
data_set = pd.read_csv('data/data_set_div_sigugun.csv')

In [7]:
data_set

,Unnamed: 0,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),동,층,건축년도,도로명,sido,gugun,dong
0,0,561,561,0,래미안 옥수 리버젠,84.81,201501.0,2,"73,000",-,12,2012,매봉길 15,서울특별시,성동구,옥수동
1,1,561,561,0,래미안 옥수 리버젠,59.25,201501.0,3,"59,500",-,12,2012,매봉길 15,서울특별시,성동구,옥수동
2,2,436,436,0,극동그린,114.32,201501.0,3,"60,000",-,7,1997,독서당로 175,서울특별시,성동구,옥수동
3,3,561,561,0,래미안 옥수 리버젠,59.25,201501.0,6,"59,000",-,11,2012,매봉길 15,서울특별시,성동구,옥수동
4,4,561,561,0,래미안 옥수 리버젠,59.25,201501.0,6,"57,000",-,4,2012,매봉길 15,서울특별시,성동구,옥수동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628200,11163,674,674,0,강일리버파크3단지,84.83,202007.0,5,"89,800",-,10,2009,아리수로93길 40,서울특별시,강동구,강일동
628201,11164,717,717,0,고덕리엔파크2단지,84.87,202007.0,4,"90,000",-,8,2011,고덕로 427,서울특별시,강동구,강일동
628202,11165,665,665,0,강일리버파크1단지,59.87,202007.0,2,"72,500",-,9,2009,아리수로93가길 25,서울특별시,강동구,강일동
628203,11166,699,699,0,강일리버파크9단지,84.53,202007.0,1,"89,990",-,7,2009,고덕로97길 29,서울특별시,강동구,강일동
628204,11167,665,665,0,강일리버파크1단지,84.53,202007.0,1,"78,000",-,4,2009,아리수로93가길 25,서울특별시,강동구,강일동

In [8]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628205 entries, 0 to 628204
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  628205 non-null  int64
 1   번지          628205 non-null  object
 2   본번          628205 non-null  int64
 3   부번          628205 non-null  int64
 4   단지명         628205 non-null  object
 5   전용면적(㎡)     628205 non-null  float64
 6   계약년월        628205 non-null  float64
 7   계약일         628205 non-null  int64
 8   거래금액(만원)    628205 non-null  object
 9   동           628205 non-null  object
 10  층           628205 non-null  int64
 11  건축년도        628205 non-null  int64
 12  도로명         628205 non-null  object
 13  sido        628205 non-null  object
 14  gugun       628205 non-null  object
 15  dong        628205 non-null  object
dtypes: float64(2), int64(6), object(8)
memory usage: 76.7+ MB

## 데이터셋 가공

In [10]:
data_set = data_set.drop(['Unnamed: 0', '계약일'], axis = 1)

In [47]:
df = data_set.drop(data_set[data_set['도로명'] == ' '].index)

In [48]:
df

,번지,본번,부번,단지명,전용면적(㎡),계약년월,거래금액(만원),동,층,건축년도,도로명,sido,gugun,dong
0,561,561,0,래미안 옥수 리버젠,84.81,201501.0,"73,000",-,12,2012,매봉길 15,서울특별시,성동구,옥수동
1,561,561,0,래미안 옥수 리버젠,59.25,201501.0,"59,500",-,12,2012,매봉길 15,서울특별시,성동구,옥수동
2,436,436,0,극동그린,114.32,201501.0,"60,000",-,7,1997,독서당로 175,서울특별시,성동구,옥수동
3,561,561,0,래미안 옥수 리버젠,59.25,201501.0,"59,000",-,11,2012,매봉길 15,서울특별시,성동구,옥수동
4,561,561,0,래미안 옥수 리버젠,59.25,201501.0,"57,000",-,4,2012,매봉길 15,서울특별시,성동구,옥수동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628200,674,674,0,강일리버파크3단지,84.83,202007.0,"89,800",-,10,2009,아리수로93길 40,서울특별시,강동구,강일동
628201,717,717,0,고덕리엔파크2단지,84.87,202007.0,"90,000",-,8,2011,고덕로 427,서울특별시,강동구,강일동
628202,665,665,0,강일리버파크1단지,59.87,202007.0,"72,500",-,9,2009,아리수로93가길 25,서울특별시,강동구,강일동
628203,699,699,0,강일리버파크9단지,84.53,202007.0,"89,990",-,7,2009,고덕로97길 29,서울특별시,강동구,강일동
628204,665,665,0,강일리버파크1단지,84.53,202007.0,"78,000",-,4,2009,아리수로93가길 25,서울특별시,강동구,강일동

In [44]:
doro = []
doro_gil = []

delete_idx = []

for i, dong_list in enumerate(list(df['도로명'].str.split())):
  if len(dong_list) == 2:
    doro.append(dong_list[0])
    doro_gil.append(dong_list[1])
  else:
    doro.append('')
    doro_gil.append(dong_list[0])

print(len(doro))
print(len(doro_gil))

print(delete_idx)

627767
627767
[]

In [45]:
df['도로명'] = doro
df['건물번호'] = doro_gil

In [98]:
df = df.drop(df[df['번지'].str.contains('가')].index)

In [99]:
df

,번지,본번,부번,단지명,전용면적(㎡),계약년월,거래금액(만원),동,층,건축년도,도로명,sido,gugun,dong,건물번호
0,561,561,0,래미안 옥수 리버젠,84.81,201501.0,"73,000",-,12,2012,매봉길,서울특별시,성동구,옥수동,15
1,561,561,0,래미안 옥수 리버젠,59.25,201501.0,"59,500",-,12,2012,매봉길,서울특별시,성동구,옥수동,15
2,436,436,0,극동그린,114.32,201501.0,"60,000",-,7,1997,독서당로,서울특별시,성동구,옥수동,175
3,561,561,0,래미안 옥수 리버젠,59.25,201501.0,"59,000",-,11,2012,매봉길,서울특별시,성동구,옥수동,15
4,561,561,0,래미안 옥수 리버젠,59.25,201501.0,"57,000",-,4,2012,매봉길,서울특별시,성동구,옥수동,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628200,674,674,0,강일리버파크3단지,84.83,202007.0,"89,800",-,10,2009,아리수로93길,서울특별시,강동구,강일동,40
628201,717,717,0,고덕리엔파크2단지,84.87,202007.0,"90,000",-,8,2011,고덕로,서울특별시,강동구,강일동,427
628202,665,665,0,강일리버파크1단지,59.87,202007.0,"72,500",-,9,2009,아리수로93가길,서울특별시,강동구,강일동,25
628203,699,699,0,강일리버파크9단지,84.53,202007.0,"89,990",-,7,2009,고덕로97길,서울특별시,강동구,강일동,29
628204,665,665,0,강일리버파크1단지,84.53,202007.0,"78,000",-,4,2009,아리수로93가길,서울특별시,강동구,강일동,25

In [107]:
price = []


for i, p_list in enumerate(list(df['거래금액(만원)'].str.split(','))):
  if len(p_list) == 3:
    price.append(int(p_list[0]) * 1000000 + int(p_list[1]) * 1000 + int(p_list[2]))
  elif len(p_list) == 2:
    price.append(int(p_list[0]) * 1000 + int(p_list[1]))
  elif len(p_list) == 1:
    price.append(int(p_list[0]))
  else:
    print(p_list)

In [110]:
df['거래금액(만원)'] = price

In [113]:
len(price)

597405

In [103]:
df = df.drop(['번지'], axis = 1)

In [112]:
df.to_csv('data/dataset_final.csv')

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 597405 entries, 0 to 628204
Data columns (total 14 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   본번        597405 non-null  int64
 1   부번        597405 non-null  int64
 2   단지명       597405 non-null  object
 3   전용면적(㎡)   597405 non-null  float64
 4   계약년월      597405 non-null  float64
 5   거래금액(만원)  597405 non-null  int64
 6   동         597405 non-null  object
 7   층         597405 non-null  int64
 8   건축년도      597405 non-null  int64
 9   도로명       597405 non-null  object
 10  sido      597405 non-null  object
 11  gugun     597405 non-null  object
 12  dong      597405 non-null  object
 13  건물번호      597405 non-null  object
dtypes: float64(2), int64(5), object(7)
memory usage: 68.4+ MB